MDScreen:
    name: 'recipe_main'
    MDFloatLayout:
        md_bg_color: 1,1,1,1
        MDLabel:
            text: "Recipes"
            pos_hint: {'center_x':.8, 'center_y':0.925}
            font_size: "35sp"
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "40sp"
            pos_hint: {'center_y': .95}
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = 'main'